### ISSUE TITLE
Mobile First Design

### ISSUE THREAD

**Issue by joe-studer-18** [mst-ka/mst-ka-site#117]
The vast majority of our clicks are coming from mobile sites. We're doing great w/ desktop traffic (pagespeed insights scores us 98/100), but pretty terrible on mobile (44/100, not that most sites do well here, but it would be an easy win if we focused on it). 

![image](https://user-images.githubusercontent.com/37095100/126911802-3c96f29a-8447-413f-9fa8-abfda7fdff2a.png)

Here are the action items that need to be completed for this issue:

* Reduce unused Javascript - pulling in JQuery feels a bit wasteful. I think we're only using it in a couple spots - we should eliminate these dependencies if possible. Additionally, the matterport Iframe doesn't support mobile anyway - we should default to a static image & a link here instead of loading all of their content. _This would be a quick, easy win_
* Instagram link - this works great on desktop, but the images are small and a bit worthless on mobile. We should either load fewer images (like 1) or just remove this on mobile sites.
* Use a [more efficient cache policy](https://web.dev/uses-long-cache-ttl/?utm_source=lighthouse&utm_medium=unknown) for static images. This one can be easy to implement, but will also mess us up quite a bit if used with too heavy of a hand. Probably need to be explicit about what images to cache (i.e. definitely not officer photos, and maybe only some of the generic style sheets)
* Reduce payload size of large images (particularly banner images)

**Comment by mat-px** [comment]
Note for images: we need to compress them and re-upload them in a smaller quality. It isn't really noticeable but it should help a bit

**Comment by mat-px** [comment]
I was looking into the documentation for caching, might help with the site since there really isn't much changing, so we don't really need to frequently update.

Not sure how to test this in the json:

    "headers": [{
      "source" : "**",
      "headers" : [{
        "key" : "Cache-Control",
        "value" : "max-age=31536000"
      }]
    }],
